[common]
DrawExtraPixelsLeft=25
DrawExtraPixelsRight=25
AdvanceExtraPixels=0

[Char Widths]
line 0=0123456789(
line 1=)/.-%+

DefaultWidth=95 # char width
AddToAllWidths=-54 # for kerning.

# make ( and ) narrower, orig is 25
10=55
11=55

# make . and - narrower
13=58
14=62

# give % extra padding
15=77
